### ISSUE TITLE
invalid_client

### ISSUE THREAD

**Issue by softshape** [pikhovkin/yametrikapy#2]
Пробуем запустить код из примера, подставив client_id своего приложения. Результат - invalid_client. Пробуем разные комбинации login / password (для приложения, для пользователя) с аналогичным результатом.

Что все-таки должно быть в параметрах client_id, login, password для корректной работы приложения?

**Comment by loopdigga98** [comment]
@pikhovkin было бы неплохо, написать в README, что апи сменилось и могут быть ошибки

**Comment by pikhovkin** [comment]
@loopdigga98, ок. Киньте текст ошибки, если получили ее.

**Comment by pikhovkin** [comment]
d0751069b827b038833affca0b7779869a9c8452
