### ISSUE TITLE
APIException: 503: Сервис временно недоступен

### ISSUE THREAD

**Issue by Techinek** [pikhovkin/yametrikapy#5]
Постоянно ловлю APIException: 503: Сервис временно недоступен. Пример простого запроса:
```
  from yametrikapy import Metrika

  metrika = Metrika(client_id, token=token)

    counters = metrika.counters().counters
    print(counters)
```

**Comment by pikhovkin** [comment]
Делайте пока так:
`counters = metrika.counters(permission='own,edit,view').counters`
или установите версию из мастер-ветки.
Видимо, эта возможность уже "исправлена"
